services:
  db:
    image: postgres:15
    container_name: health-track-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: miocardio2
      POSTGRES_DB: health_db
    ports:
      - "5432:5432"